### PR TITLE
Fix inconsistent size on smart bulletin h1

### PR DESCRIPTION
**Pull request by brentryanjohnson**
- The Smart Bulletins `h1` is smaller than `h1`s on other pages
  - The `h1` on Smart Bulletins is styled at `2em`, while those on other pages are styled at `2.44rem`

- This appears to be caused by the Smart Bulletins astro layout lacking `usa-prose` classes on the `main` element that the other pages have
- This PR adds the `main` classes to fix the inconsistent font size

## Policies page
Screenshot showing Policies title and a table

## Smart Bulletins page
Screenshot showing Smart Bulletins page title and a table

### CODE REVIEW

**Review by weiwang-gsa — CHANGES_REQUESTED** [review]
Hi Ryan, if usa-pose class added to main, it will make the content width not full size, see screenshot, that is the original reason why those class are removed. You can add that usa-prose class to h1 tag though. 

image

**Comment by brentryanjohnson** [comment]
@weiwang-gsa Should that also be true of the Policies page, since it's full width? It looks like it has the `usa-prose` classes on `main`. I can fix both in my branch, if so.

**Comment by brentryanjohnson** [comment]
Hmmm...the class can't be applied directly to the `h1` because it applies to the children of a container. We might need to add a `div`. I'll experiment with it.

**Comment by brentryanjohnson** [comment]
This is a bigger problem, so closing the PR and adding an issue instead.

**Comment by brentryanjohnson** [comment]
Okay...this solution isn't perfect, but it wraps just the `h1` in a `div` with the `usa-prose` class to fix font size styling. Fixes #266

**Comment by mark-meyer** [comment]
@weiwang-gsa and @brentryanjohnson Sorry, coming to this one a little late...Are `h1` headings supposed to be the same size globally? If so, can we just change the sass for it?

**Comment by brentryanjohnson** [comment]
@mark-meyer @weiwang-gsa I think we should probably just custom style the `h1`. Otherwise, for future full-page layouts, they'll have to do this `usa-prose` gymnastics all over again.

**Comment by brentryanjohnson** [comment]
Closing in favor of styling `h1`s independent of `usa-prose`.

**Pull request closed without merging**
