### PR TITLE
Add redirects from old site to this one

### PR DESCRIPTION
**Pull request by jfredrickson5**
Addresses #84 

- Bump Astro to 2.9.7 to get the [Configured Redirects](https://docs.astro.build/en/core-concepts/routing/#configured-redirects) feature
- Add redirects per [IA sheet](https://docs.google.com/spreadsheets/d/1-nIXpGYsCgKcrXA4LLTEECBILCZOVWmn4n4abvFJGZU/edit?usp=sharing)
- Add a filter function to the sitemap to exclude redirects from the sitemap

### CODE REVIEW

**Review by weiwang-gsa — APPROVED** [review]
LGTM

**Review by mark-meyer — APPROVED** [review]
Looks good to — just one comment to see if we fix one more thing on American Samoa.

**Comment by jfredrickson5** [comment]
@weiwang-gsa thanks for catching that. I tweaked it a bit with the most recent commit. It should now handle paths properly on the Pages preview. @mark-meyer I threw in the American Samoa link fix as well.

**Review by weiwang-gsa — APPROVED** [review]
LGTM!

**Pull request merged**
