### PR TITLE
Updates logos and designs to design mockup

### PR DESCRIPTION
**Pull request by brentryanjohnson**
- Updates logos and designs (in `About` section) to match Figma update
- Updates to table format (inline HTML)
- Adds table cell heading for `Download` (not in mock) for accessibility for that column
- Omits "Note:" from mockup because implied

## Dev notes
- This updates what we previously merged (About section #152)
- This uses inline HTML for the table (within the markdown file); dev may have a better option for this
- I couldn't use the card and logo assets already in `src` (because they're not available for this use in markdown), so I created thumbnails for each preview image

## Preview

screenshot with table presenting download options for the smartpay logo, travel, fleet, purchase, integrated, and tax advantage cards, along with card image thumbnails

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@mark-meyer This might be another good candidate for mdx + component (for the table).

**Review by klohman — APPROVED** [review]

**Review by weiwang-gsa — COMMENTED** [review]
Just let you know that currently from preview build, images are not rendering on server side. you can use markdown image syntax instead

**Comment by brentryanjohnson** [comment]
Closing this one (for now) so dev can advise on a table component and image paths in previews.

**Comment by brentryanjohnson** [comment]
@weiwang-gsa I confirmed that I can't use markdown syntax in the HTML table, and I can't use a markdown _table_ because (to my knowledge) we don't have a way to attach the CSS class to a markdown element (the table requires a USWDS class).

I'm closing so you and the other engineers can review for options.

**Comment by brentryanjohnson** [comment]
Reopening this PR

- Converts `md` file to `mdx` to use markdown in HTML (and fix relative link paths in previews)

**Comment by brentryanjohnson** [comment]
[🔍 Preview](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/rj-logos-designs/about/logos/)

**Comment by klohman** [comment]
> [🔍 Preview](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/rj-logos-designs/about/logos/)
@brentryanjohnson 

The SmartPay logo here looks blurry even at a small size. I'm not sure which version you used, but this is the [SVG file](https://drive.google.com/file/d/1qDgxa6BdcINnsl_WFdjT8jCnYvwNyTn8/view?usp=drive_link) Wei used for the header

**Review by mark-meyer — APPROVED** [review]
LGTM!

**Pull request merged**
